"use client";

import { useState } from "react";
import { MessageCircle } from "lucide-react";
import { useCart } from "@/components/cart/cart-provider";
import { formatPrice } from "@/lib/cart/cart-utils";
import { Button } from "@/components/ui/button";
import type { SiteSettings } from "@/lib/types";

export function WhatsAppCheckout({ settings }: { settings: SiteSettings | null }) { const { items, total } = useCart(); const initialFulfillment = settings?.pickup_enabled ? "استلام من المحل" : "توصيل"; const [form, setForm] = useState({ name: "", phone: "", fulfillment: initialFulfillment, address: "", date: "", time: "", notes: "" }); const [error, setError] = useState(""); const currencySymbol = settings?.currency_symbol ?? items[0]?.currencySymbol ?? ""; const fulfillmentOptions = [settings?.pickup_enabled && "استلام من المحل", settings?.delivery_enabled && "توصيل"].filter(Boolean) as string[]; function submit(event: React.FormEvent) { event.preventDefault(); const number = settings?.whatsapp_number; if (!items.length) { setError("أضيفي منتجاً واحداً على الأقل قبل إرسال الطلب."); return; } if (!number) { setError("الطلب عبر واتساب غير متاح حالياً."); return; } const lines = items.map((item, index) => `${index + 1}. ${item.name}\n   الحجم: ${item.size ?? "-"}\n   النكهة: ${item.flavor ?? "-"}\n   العدد: ${item.quantity}\n   ${item.customMessage ? `الكتابة على الكيك: ${item.customMessage}\n   ` : ""}السعر: ${formatPrice(item.unitPrice * item.quantity, currencySymbol)}`).join("\n\n"); const message = `مرحباً ${settings.store_name} 👋\n\nأرغب في طلب المنتجات التالية:\n\nالاسم: ${form.name}\nرقم الهاتف: ${form.phone}\n\nالطلبات:\n\n${lines}\n\nالإجمالي: ${formatPrice(total, currencySymbol)}\n\nطريقة الاستلام: ${form.fulfillment}\n${form.fulfillment === "توصيل" ? `العنوان: ${form.address}\n` : ""}التاريخ المطلوب: ${form.date}\nالوقت المفضل: ${form.time}\nملاحظات: ${form.notes || "لا توجد"}\n\nبعد فتح واتساب يمكنك إرسال صورة التصميم الذي تريده مباشرة للمحل.\n\nشكراً.`; window.open(`https://wa.me/${number.replace(/\D/g, "")}?text=${encodeURIComponent(message)}`, "_blank", "noopener,noreferrer"); }
  return <section className="container-wide grid gap-10 py-12 sm:py-20 lg:grid-cols-[1fr_.42fr]"><form onSubmit={submit} className="rounded-[2rem] bg-white/60 p-6 sm:p-10"><div className="grid gap-5 sm:grid-cols-2"><label className="text-xs text-ink/55">الاسم<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="form-input" placeholder="الاسم الكامل" /></label><label className="text-xs text-ink/55">رقم الهاتف<input required value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} className="form-input" placeholder="٠٥٠…" /></label>{fulfillmentOptions.length > 0 && <label className="text-xs text-ink/55 sm:col-span-2">طريقة الاستلام<select value={form.fulfillment} onChange={(e) => setForm({ ...form, fulfillment: e.target.value })} className="form-input">{fulfillmentOptions.map((item) => <option key={item}>{item}</option>)}</select></label>}{form.fulfillment === "توصيل" && <label className="text-xs text-ink/55 sm:col-span-2">العنوان<input required value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} className="form-input" placeholder="الحي، الشارع، رقم المبنى" /></label>}<label className="text-xs text-ink/55">التاريخ المطلوب<input required type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} className="form-input" /></label><label className="text-xs text-ink/55">الوقت المفضل<input required value={form.time} onChange={(e) => setForm({ ...form, time: e.target.value })} className="form-input" placeholder="مثال: ٧ مساءً" /></label><label className="text-xs text-ink/55 sm:col-span-2">ملاحظات إضافية<textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} rows={4} className="form-input resize-none" placeholder="أي تفاصيل إضافية…" /></label></div>{error && <p className="mt-5 rounded-xl bg-burgundy/10 p-3 text-xs text-burgundy">{error}</p>}<Button disabled={!settings?.whatsapp_number || fulfillmentOptions.length === 0} className="mt-7" type="submit"><MessageCircle size={17} /> إرسال الطلب عبر واتساب</Button></form><aside className="h-fit rounded-[1.5rem] bg-cocoa p-7 text-cream"><p className="eyebrow text-gold">ماذا سيحدث؟</p><ol className="mt-6 space-y-5 text-sm leading-7 text-cream/70"><li><span className="ml-2 text-gold">٠١</span> نجهز لك رسالة الطلب بكل التفاصيل.</li><li><span className="ml-2 text-gold">٠٢</span> يفتح واتساب على الرقم الذي حدده المتجر.</li><li><span className="ml-2 text-gold">٠٣</span> راجعي الرسالة واضغطي إرسال.</li></ol><p className="mt-8 border-t border-cream/15 pt-6 text-xs leading-6 text-cream/45">لن يتم حفظ الطلب في الموقع أو Supabase.</p></aside></section>; }
