"use client";

import Link from "next/link";
import { Heart, Menu, Search, ShoppingBag, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { Category, SiteSettings } from "@/lib/types";
import { SearchOverlay } from "./search-overlay";
import { useCart } from "@/components/cart/cart-provider";

export function SiteHeader({ settings, categories }: { settings: SiteSettings | null; categories: Category[] }) {
  const [scrolled, setScrolled] = useState(false); const [open, setOpen] = useState(false); const [search, setSearch] = useState(false); const { items } = useCart();
  const nav = useMemo(() => [["الرئيسية", "/"], ...categories.slice(0, 3).map((category) => [category.name_ar, `/shop?category=${category.slug}`]), ["المناسبات", "/occasions"], ["صمم كيكك", "/custom-cake"], ["عن المتجر", "/about"], ["تواصل معنا", "/contact"]] as Array<[string, string]>, [categories]);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 28); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  return <><header className={`fixed inset-x-0 top-0 z-40 transition-all duration-500 ${scrolled ? "bg-cream/95 shadow-sm backdrop-blur-md" : "bg-transparent"}`}><div className="container-wide flex h-[78px] items-center justify-between gap-6"><Link href="/" className="group shrink-0" aria-label="الصفحة الرئيسية"><span className="font-serif text-[2.2rem] leading-none tracking-[-0.07em]">{settings?.store_name ?? "المتجر"}</span>{settings?.store_name_ar && <span className="mr-2 align-top text-[9px] font-semibold tracking-[0.25em] text-gold">{settings.store_name_ar}</span>}</Link><nav className="hidden items-center gap-5 xl:flex">{nav.map(([label, href]) => <Link key={href} href={href} className="text-[13px] text-ink/75 transition hover:text-rose">{label}</Link>)}</nav><div className="flex items-center gap-1 sm:gap-2"><button className="icon-btn" aria-label="البحث" onClick={() => setSearch(true)}><Search size={18} strokeWidth={1.5} /></button><Link className="icon-btn hidden sm:inline-flex" href="/favorites" aria-label="المفضلة"><Heart size={18} strokeWidth={1.5} /></Link><Link className="icon-btn" href="/cart" aria-label="السلة"><ShoppingBag size={18} strokeWidth={1.5} />{items.length > 0 && <span className="absolute -right-0.5 -top-0.5 flex h-3.5 w-3.5 items-center justify-center rounded-full bg-burgundy text-[8px] text-white">{items.reduce((sum, item) => sum + item.quantity, 0)}</span>}</Link><button className="icon-btn xl:hidden" aria-label="القائمة" onClick={() => setOpen(!open)}>{open ? <X size={21} /> : <Menu size={21} />}</button></div></div>{open && <div className="border-t hairline bg-cream px-5 pb-7 pt-4 xl:hidden"><nav className="flex flex-col gap-4">{nav.map(([label, href]) => <Link key={href} href={href} onClick={() => setOpen(false)} className="border-b hairline pb-3 text-base">{label}</Link>)}</nav></div>}</header>{search && <SearchOverlay onClose={() => setSearch(false)} />}</>;
}
