"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, Instagram, Sparkles } from "lucide-react";
import { motion } from "framer-motion";
import type { Category, GalleryItem, HomepageSection, Product, Promotion, SiteSettings } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { ImageCard } from "@/components/ui/image-card";
import { ProductCard } from "@/components/product-card";
import { SectionHeading } from "@/components/section-heading";

const fadeUp = { hidden: { opacity: 0, y: 22 }, visible: { opacity: 1, y: 0, transition: { duration: 0.7 } } };
const getSection = (sections: HomepageSection[], key: HomepageSection["section_key"]) => sections.find((section) => section.section_key === key) ?? null;

function DynamicImage({ src, alt, className, sizes }: { src: string | null; alt: string; className?: string; sizes: string }) { const isHeroBackground = className?.includes("absolute inset-0"); return <div className={`relative overflow-hidden bg-[#2d201d] ${className ?? ""}`}>{src ? <Image src={src} alt={alt} fill sizes={sizes} className="object-cover" /> : <span className="flex h-full items-center justify-center text-xs text-cream/50">الصورة غير متاحة</span>}{isHeroBackground && <video aria-hidden="true" autoPlay loop muted playsInline poster={src ?? "/brand/victoria-logo.png"} preload="metadata" tabIndex={-1} className="absolute inset-0 h-full w-full object-cover object-[center_45%] transition-opacity duration-700 sm:object-center"><source src="/videos/victoria-hero.mp4" type="video/mp4" /></video>}</div>; }

export function HomePage({ products, categories, settings, sections, gallery, promotions }: { products: Product[]; categories: Category[]; settings: SiteSettings | null; sections: HomepageSection[]; gallery: GalleryItem[]; promotions: Promotion[] }) {
  const hero = getSection(sections, "hero"); const customCake = getSection(sections, "custom_cake"); const chocolate = getSection(sections, "chocolate"); const gift = getSection(sections, "gift"); const about = getSection(sections, "about"); const featured = products.filter((product) => product.is_featured); const bestSellers = products.filter((product) => product.is_best_seller); const displayProducts = bestSellers.length ? bestSellers : featured;
  if (!hero && !categories.length && !displayProducts.length) return <main className="container-wide flex min-h-[60vh] items-center justify-center pt-28"><p className="rounded-2xl bg-white/60 p-8 text-center text-sm text-ink/55">نقوم بتجهيز محتوى المتجر. يرجى العودة قريباً.</p></main>;
  return <main>{hero && <section className="relative min-h-[720px] overflow-hidden bg-cocoa pt-28 text-cream sm:min-h-[780px]"><DynamicImage src={hero.image_url} alt={hero.title_ar ?? "صورة القسم الرئيسي"} sizes="100vw" className="absolute inset-0" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(45,32,29,.78),rgba(45,32,29,.26),rgba(45,32,29,.14))]" /><div className="container-wide relative flex min-h-[590px] items-end pb-20 sm:pb-28"><motion.div initial="hidden" animate="visible" variants={fadeUp} className="max-w-xl"><p className="eyebrow mb-6 text-cream/70">{settings?.tagline_ar ?? settings?.store_name_ar}</p><h1 className="max-w-lg font-serif text-5xl leading-[1.05] tracking-[-0.05em] sm:text-7xl lg:text-[5.8rem]">{hero.title_ar}</h1>{hero.subtitle_ar && <p className="mt-7 max-w-md text-sm leading-8 text-cream/75 sm:text-base">{hero.subtitle_ar}</p>}<div className="mt-8 flex flex-wrap gap-3">{hero.button_text_ar && hero.button_link && <Link href={hero.button_link}><Button className="bg-cream text-ink hover:bg-white">{hero.button_text_ar}<ArrowLeft size={16} /></Button></Link>}{hero.secondary_button_text_ar && hero.secondary_button_link && <Link href={hero.secondary_button_link}><Button variant="outline" className="border-cream/45 text-cream hover:bg-cream hover:text-ink">{hero.secondary_button_text_ar}</Button></Link>}</div></motion.div></div></section>}
    {categories.length > 0 && <section className="container-wide py-20 sm:py-28"><SectionHeading eyebrow="التصنيفات" title="اختر ما يجعل مناسبتك أجمل" /><div className="grid gap-4 sm:grid-cols-2">{categories.slice(0, 6).map((category, index) => <ImageCard key={category.id} href={`/shop?category=${category.slug}`} image={category.image_url} title={category.name_ar} subtitle={category.description_ar ?? undefined} className={`aspect-[1.05] ${index % 2 ? "sm:translate-y-12" : ""}`} />)}</div></section>}
    {displayProducts.length > 0 && <section className="bg-[#eee7dc] py-20 sm:py-28"><div className="container-wide"><SectionHeading eyebrow="اختياراتكم المفضلة" title={bestSellers.length ? "الأكثر طلباً" : "اختيارات مميزة"} link={{ label: "عرض كل المنتجات", href: "/shop" }} /><div className="grid grid-cols-2 gap-x-4 gap-y-10 sm:grid-cols-3 lg:grid-cols-4">{displayProducts.slice(0, 4).map((product) => <ProductCard key={product.slug} product={product} currencySymbol={settings?.currency_symbol ?? ""} />)}</div></div></section>}
    {customCake && <section className="container-wide py-20 sm:py-32"><div className="relative overflow-hidden rounded-[2.5rem] bg-cocoa px-6 py-16 text-cream sm:px-14 sm:py-24"><div className="relative grid items-center gap-12 lg:grid-cols-[1fr_.85fr]"><div className="max-w-xl"><p className="eyebrow text-gold">تجربة مخصصة</p><h2 className="mt-5 font-serif text-5xl leading-[1.05] tracking-[-0.04em] sm:text-7xl">{customCake.title_ar}</h2>{customCake.subtitle_ar && <p className="mt-6 max-w-md text-sm leading-8 text-cream/70">{customCake.subtitle_ar}</p>}{customCake.button_text_ar && customCake.button_link && <Link href={customCake.button_link}><Button className="mt-8 bg-cream text-ink hover:bg-white">{customCake.button_text_ar}<ArrowLeft size={16} /></Button></Link>}</div><DynamicImage src={customCake.image_url} alt={customCake.title_ar ?? "كيك مخصص"} sizes="(max-width: 1024px) 80vw, 35vw" className="mx-auto aspect-square w-full max-w-sm rounded-full border-[10px] border-cream/10" /></div></div></section>}
    {promotions.map((promotion) => <section className="container-wide pb-20 sm:pb-28" key={promotion.id}><div className="grid overflow-hidden rounded-[2rem] bg-[#eee7dc] sm:grid-cols-2"><DynamicImage src={promotion.image_url} alt={promotion.title_ar} sizes="50vw" className="min-h-[260px]" /><div className="flex flex-col justify-center p-8 sm:p-12"><p className="eyebrow">عرض خاص</p><h2 className="mt-4 font-serif text-4xl">{promotion.title_ar}</h2>{promotion.description_ar && <p className="mt-4 text-sm leading-8 text-ink/60">{promotion.description_ar}</p>}{promotion.button_text_ar && promotion.button_link && <Link className="mt-6 inline-flex items-center gap-2 text-sm text-burgundy" href={promotion.button_link}>{promotion.button_text_ar}<ArrowLeft size={16} /></Link>}</div></div></section>)}
    {chocolate && <section className="container-wide grid gap-10 py-20 sm:py-32 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="eyebrow">الشوكولاتة</p><h2 className="display-title mt-4">{chocolate.title_ar}</h2>{chocolate.subtitle_ar && <p className="mt-6 max-w-md text-sm leading-8 text-ink/60">{chocolate.subtitle_ar}</p>}{chocolate.button_text_ar && chocolate.button_link && <Link href={chocolate.button_link} className="mt-8 inline-flex items-center gap-2 border-b border-gold pb-2 text-sm">{chocolate.button_text_ar}<ArrowLeft size={16} /></Link>}</div><DynamicImage src={chocolate.image_url} alt={chocolate.title_ar ?? "الشوكولاتة"} sizes="(max-width: 1024px) 100vw, 50vw" className="aspect-[1.15] rounded-[2rem]" /></section>}
    {gift && <section className="bg-ink py-20 text-cream sm:py-28"><div className="container-wide grid items-center gap-12 lg:grid-cols-[1fr_1fr]"><div><p className="eyebrow text-gold">هديتك على ذوقك</p><h2 className="display-title mt-4">{gift.title_ar}</h2>{gift.subtitle_ar && <p className="mt-6 max-w-md text-sm leading-8 text-cream/60">{gift.subtitle_ar}</p>}{gift.button_text_ar && gift.button_link && <Link href={gift.button_link}><Button className="mt-8 bg-rose text-cream hover:bg-rose/80">{gift.button_text_ar}<ArrowLeft size={16} /></Button></Link>}</div><DynamicImage src={gift.image_url} alt={gift.title_ar ?? "هدية"} sizes="(max-width: 1024px) 100vw, 45vw" className="aspect-[1.3] rounded-[2rem]" /></div></section>}
    {about && <section className="container-wide grid gap-10 py-20 sm:py-32 lg:grid-cols-[1fr_1fr] lg:items-center"><DynamicImage src={about.image_url} alt={about.title_ar ?? "عن المتجر"} sizes="(max-width: 1024px) 100vw, 50vw" className="aspect-[.9] rounded-[2rem]" /><div className="lg:pr-10"><p className="eyebrow">عن {settings?.store_name_ar ?? settings?.store_name}</p><h2 className="display-title mt-4">{about.title_ar}</h2>{about.subtitle_ar && <p className="mt-6 max-w-lg text-sm leading-8 text-ink/60">{about.subtitle_ar}</p>}{about.button_text_ar && about.button_link && <Link href={about.button_link} className="mt-8 inline-flex items-center gap-2 border-b border-gold pb-2 text-sm">{about.button_text_ar}<ArrowLeft size={16} /></Link>}</div></section>}
    {gallery.length > 0 && <section className="bg-[#eee7dc] py-20 sm:py-28"><div className="container-wide"><div className="mb-10 flex items-end justify-between"><div><p className="eyebrow">معرض الصور</p><h2 className="display-title mt-3 text-3xl sm:text-5xl">لحظات من {settings?.store_name ?? ""}</h2></div>{settings?.instagram_url && <a href={settings.instagram_url} target="_blank" rel="noreferrer" aria-label="إنستغرام"><Instagram className="text-gold" size={27} strokeWidth={1.3} /></a>}</div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{gallery.slice(0, 6).map((item, index) => <DynamicImage key={item.id} src={item.image_url} alt={item.caption_ar ?? "صورة من المعرض"} sizes="25vw" className={`aspect-square rounded-3xl ${index === 0 ? "sm:row-span-2 sm:aspect-auto" : ""}`} />)}</div></div></section>}
    <section className="container-wide pb-20 pt-20 sm:pb-28"><div className="relative overflow-hidden rounded-[2rem] bg-rose px-6 py-14 text-center text-cream sm:px-10 sm:py-20"><Sparkles className="mx-auto text-cream/70" size={24} /><h2 className="mx-auto mt-4 max-w-2xl font-serif text-4xl sm:text-6xl">{settings?.tagline_ar}</h2>{settings?.description_ar && <p className="mx-auto mt-5 max-w-md text-sm leading-7 text-cream/75">{settings.description_ar}</p>}<div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/shop"><Button className="bg-cream text-ink hover:bg-white">تسوق الآن</Button></Link>{settings?.whatsapp_number && <Link href="/checkout"><Button variant="outline" className="border-cream/50 text-cream hover:bg-cream hover:text-ink">اطلب عبر واتساب</Button></Link>}</div></div></section>
  </main>;
}
