"use client";

import { ArrowLeft, Check, ChevronRight } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";

const steps = [{ title: "المناسبة", options: ["عيد ميلاد", "تخرج", "زفاف", "خطوبة", "طفل جديد", "مناسبة خاصة"] }, { title: "الحجم", options: ["صغير — ٤ أشخاص", "متوسط — ٨ أشخاص", "كبير — ١٢ شخصاً"] }, { title: "النكهة", options: ["شوكولاتة داكنة", "فانيلا وفراولة", "ريد فيلفت", "كراميل مملح"] }, { title: "التصميم", options: ["أتركها لذوقكم", "سأرفق صورة مرجعية", "تصميم بسيط وأنيق"] }];

export function CustomCakeWizard() { const [step, setStep] = useState(0); const [selected, setSelected] = useState<string[]>([]); const done = step >= steps.length; const current = steps[Math.min(step, steps.length - 1)]; const select = (option: string) => { const next = [...selected]; next[step] = option; setSelected(next); }; return <section className="container-wide py-12 sm:py-20"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><aside><p className="eyebrow">رحلة تصميم كيكك</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">نصنع الفكرة<br /><em className="text-rose">كما تتخيلينها</em></h2><p className="mt-5 max-w-sm text-sm leading-8 text-ink/60">أخبرينا عن مناسبتك، وسنحولها إلى قطعة حلوى تشبهك.</p><div className="mt-10 hidden space-y-4 lg:block">{steps.map((item, i) => <div key={item.title} className={`flex items-center gap-3 text-sm ${i === step ? "text-ink" : "text-ink/35"}`}><span className={`flex h-8 w-8 items-center justify-center rounded-full border ${i < step ? "border-burgundy bg-burgundy text-white" : "hairline"}`}>{i < step ? <Check size={15} /> : `0${i + 1}`}</span>{item.title}</div>)}</div></aside><div className="rounded-[2rem] bg-white/60 p-5 sm:p-9"><div className="mb-8 flex items-center justify-between text-xs text-ink/40"><span>الخطوة {Math.min(step + 1, steps.length)} من {steps.length}</span><span className="h-1 w-32 overflow-hidden rounded-full bg-ink/10"><span className="block h-full rounded-full bg-rose transition-all" style={{ width: `${((step + 1) / steps.length) * 100}%` }} /></span></div>{done ? <div className="py-16 text-center"><span className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-burgundy text-white"><Check /></span><h3 className="mt-6 font-serif text-4xl">وصلتنا فكرتك</h3><p className="mx-auto mt-4 max-w-sm text-sm leading-7 text-ink/60">سيتواصل معك فريق فيكتوريا خلال يوم عمل لتأكيد التفاصيل والسعر.</p><Button className="mt-8" onClick={() => { setStep(0); setSelected([]); }}>ابدأ تصميماً جديداً</Button></div> : <><h3 className="font-serif text-3xl">اختيار {current.title}</h3><div className="mt-7 grid gap-3 sm:grid-cols-2">{current.options.map((option) => <button key={option} onClick={() => select(option)} className={`flex items-center justify-between rounded-2xl border p-4 text-right text-sm transition ${selected[step] === option ? "border-burgundy bg-burgundy text-white" : "hairline hover:border-rose"}`}>{option}<ChevronRight size={16} className="rotate-180 opacity-50" /></button>)}</div><div className="mt-9 flex justify-between"><button disabled={step === 0} onClick={() => setStep(step - 1)} className="text-sm text-ink/50 disabled:opacity-20">رجوع</button><Button disabled={!selected[step]} onClick={() => setStep(step + 1)}>التالي <ArrowLeft size={16} /></Button></div></>}</div></div></section>; }
