export type ProductOptionType = "size" | "flavor";

export interface Category { id: string; name_ar: string; slug: string; description_ar: string | null; image_url: string | null; storage_path: string | null; sort_order: number; is_active: boolean; }
export interface ProductImage { id: string; product_id: string; image_url: string; storage_path: string | null; alt_text_ar: string | null; sort_order: number; }
export interface ProductOption { id: string; product_id: string; type: ProductOptionType; name_ar: string; price_modifier: number; sort_order: number; is_available: boolean; }
export interface Product { id: string; name_ar: string; slug: string; description_ar: string | null; short_description_ar: string | null; price: number; category_id: string | null; primary_image_url: string | null; is_available: boolean; is_featured: boolean; is_best_seller: boolean; allow_custom_message: boolean; allow_flavor_selection: boolean; allow_size_selection: boolean; sort_order: number; category: Category | null; images: ProductImage[]; options: ProductOption[]; }
export interface CartItem { lineId: string; productId: string; slug: string; name: string; image: string | null; size?: string; flavor?: string; customMessage?: string; quantity: number; unitPrice: number; currencySymbol: string; }
export interface ProductFormPayload { name_ar: string; slug: string; short_description_ar: string; description_ar: string; price: number; category_id: string | null; is_available: boolean; is_featured: boolean; is_best_seller: boolean; allow_custom_message: boolean; allow_flavor_selection: boolean; allow_size_selection: boolean; options: Array<{ type: ProductOptionType; name_ar: string; price_modifier: number }>; }

export type OpeningHour = { label_ar: string; value_ar: string };
export interface SiteSettings { id: string; store_name: string; store_name_ar: string; tagline_ar: string | null; description_ar: string | null; whatsapp_number: string | null; phone_number: string | null; email: string | null; instagram_url: string | null; facebook_url: string | null; tiktok_url: string | null; address_ar: string | null; google_maps_url: string | null; currency: string; currency_symbol: string; delivery_enabled: boolean; pickup_enabled: boolean; default_delivery_note_ar: string | null; opening_hours: OpeningHour[]; footer_note_ar: string | null; }
export interface HomepageSection { id: string; section_key: "hero" | "custom_cake" | "chocolate" | "gift" | "about"; title_ar: string | null; subtitle_ar: string | null; button_text_ar: string | null; button_link: string | null; secondary_button_text_ar: string | null; secondary_button_link: string | null; image_url: string | null; mobile_image_url: string | null; storage_path: string | null; is_active: boolean; sort_order: number; }
export interface GalleryItem { id: string; image_url: string; storage_path: string | null; caption_ar: string | null; sort_order: number; is_active: boolean; }
export interface Promotion { id: string; title_ar: string; description_ar: string | null; image_url: string | null; storage_path: string | null; button_text_ar: string | null; button_link: string | null; placement: "homepage" | "cakes" | "chocolate"; start_at: string | null; end_at: string | null; is_active: boolean; sort_order: number; }
export interface SiteSettingsPayload { store_name: string; store_name_ar: string; tagline_ar: string; description_ar: string; whatsapp_number: string; phone_number: string; email: string; instagram_url: string; facebook_url: string; tiktok_url: string; address_ar: string; google_maps_url: string; currency: string; currency_symbol: string; delivery_enabled: boolean; pickup_enabled: boolean; default_delivery_note_ar: string; opening_hours: OpeningHour[]; footer_note_ar: string; }
