"use server";

import { revalidatePath } from "next/cache";
import { getSupabaseServerClient, isCurrentAdmin } from "@/lib/supabase/server";
import type { HomepageSection, ProductFormPayload, Promotion, SiteSettingsPayload } from "@/lib/types";
import { getHomepageSectionRoute, getTrustedInternalRoute, isInternalApplicationRoute } from "@/lib/navigation/internal-routes";

async function requireAdmin() { const supabase = await getSupabaseServerClient(); if (!await isCurrentAdmin() || !supabase) throw new Error("غير مصرح"); return supabase; }

export async function createProduct(payload: ProductFormPayload) { const supabase = await requireAdmin(); const { options: selectedOptions, ...productPayload } = payload; const { data, error } = await supabase.from("products").insert(productPayload).select("id").single(); if (error || !data) throw new Error("تعذر حفظ المنتج"); const options = selectedOptions.map((option, index) => ({ ...option, product_id: data.id, sort_order: index })); if (options.length) { const optionResult = await supabase.from("product_options").insert(options); if (optionResult.error) throw new Error("تم حفظ المنتج لكن تعذر حفظ الخيارات"); } revalidatePath("/"); revalidatePath("/shop"); return { id: data.id };
}

export async function updateProduct(id: string, payload: ProductFormPayload) { const supabase = await requireAdmin(); const { options: nextOptions, ...productPayload } = payload; const { error } = await supabase.from("products").update(productPayload).eq("id", id); if (error) throw new Error("تعذر حفظ التغييرات"); const remove = await supabase.from("product_options").delete().eq("product_id", id); if (remove.error) throw new Error("تعذر تحديث خيارات المنتج"); if (nextOptions.length) { const optionResult = await supabase.from("product_options").insert(nextOptions.map((option, index) => ({ ...option, product_id: id, sort_order: index }))); if (optionResult.error) throw new Error("تعذر حفظ خيارات المنتج"); } revalidatePath("/"); revalidatePath("/shop"); revalidatePath(`/products/${payload.slug}`); return { ok: true };
}

export async function deleteProduct(id: string) { const supabase = await requireAdmin(); const { data: product } = await supabase.from("products").select("slug").eq("id", id).maybeSingle(); const { data: images } = await supabase.from("product_images").select("storage_path").eq("product_id", id); const { error } = await supabase.from("products").delete().eq("id", id); if (error) throw new Error("تعذر حذف المنتج"); const paths = (images ?? []).map((image) => image.storage_path).filter((path): path is string => Boolean(path)); if (paths.length) await supabase.storage.from("product-images").remove(paths); revalidatePath("/"); revalidatePath("/shop"); if (product?.slug) revalidatePath(`/products/${product.slug}`); return { ok: true }; }
export async function toggleProductAvailability(id: string, isAvailable: boolean) { const supabase = await requireAdmin(); const { error } = await supabase.from("products").update({ is_available: isAvailable }).eq("id", id); if (error) throw new Error("تعذر تحديث التوفر"); revalidatePath("/"); revalidatePath("/shop"); return { ok: true }; }
export async function addProductImage(productId: string, imageUrl: string, storagePath: string, altText: string) { const supabase = await requireAdmin(); const { count } = await supabase.from("product_images").select("id", { count: "exact", head: true }).eq("product_id", productId); const { error } = await supabase.from("product_images").insert({ product_id: productId, image_url: imageUrl, storage_path: storagePath, alt_text_ar: altText, sort_order: count ?? 0 }); if (error) throw new Error("تعذر حفظ الصورة"); const { data: product } = await supabase.from("products").select("primary_image_url, slug").eq("id", productId).single(); if (!product?.primary_image_url) await supabase.from("products").update({ primary_image_url: imageUrl }).eq("id", productId); revalidatePath("/"); revalidatePath("/shop"); if (product?.slug) revalidatePath(`/products/${product.slug}`); revalidatePath(`/admin/products/${productId}/edit`); return { ok: true }; }
export async function removeProductImage(imageId: string, storagePath: string | null) { const supabase = await requireAdmin(); const { error } = await supabase.from("product_images").delete().eq("id", imageId); if (error) throw new Error("تعذر حذف الصورة"); if (storagePath) await supabase.storage.from("product-images").remove([storagePath]); return { ok: true }; }
export async function setPrimaryProductImage(productId: string, imageUrl: string) { const supabase = await requireAdmin(); const { error } = await supabase.from("products").update({ primary_image_url: imageUrl }).eq("id", productId); if (error) throw new Error("تعذر تعيين الصورة الرئيسية"); revalidatePath("/"); revalidatePath("/shop"); revalidatePath(`/admin/products/${productId}/edit`); return { ok: true }; }

export async function createCategory(payload: { name_ar: string; slug: string; description_ar: string; image_url: string; storage_path?: string | null; sort_order: number }) { const supabase = await requireAdmin(); const { data, error } = await supabase.from("categories").insert(payload).select("id").single(); if (error || !data) throw new Error("تعذر إضافة التصنيف"); revalidatePath("/"); revalidatePath("/shop"); return { id: data.id }; }
export async function updateCategory(id: string, payload: { name_ar: string; slug: string; description_ar: string; image_url: string; storage_path?: string | null; sort_order: number; is_active: boolean }) { const supabase = await requireAdmin(); const { error } = await supabase.from("categories").update(payload).eq("id", id); if (error) throw new Error("تعذر تحديث التصنيف"); revalidatePath("/"); revalidatePath("/shop"); return { ok: true }; }
export async function deleteCategory(id: string, storagePath?: string | null) { const supabase = await requireAdmin(); const { error } = await supabase.from("categories").delete().eq("id", id); if (error) throw new Error("تعذر حذف التصنيف"); if (storagePath) await supabase.storage.from("product-images").remove([storagePath]); revalidatePath("/"); revalidatePath("/shop"); return { ok: true }; }

export async function saveSiteSettings(payload: SiteSettingsPayload) { const supabase = await requireAdmin(); const { data: current } = await supabase.from("site_settings").select("id").limit(1).maybeSingle(); const result = current ? await supabase.from("site_settings").update(payload).eq("id", current.id) : await supabase.from("site_settings").insert(payload); if (result.error) throw new Error("تعذر حفظ إعدادات الموقع"); revalidatePath("/", "layout"); revalidatePath("/"); revalidatePath("/contact"); revalidatePath("/checkout"); return { ok: true }; }
export async function saveHomepageSection(payload: Omit<HomepageSection, "id"> & { id?: string }) { const supabase = await requireAdmin(); const { id, ...values } = payload; const protectedValues = { ...values, button_link: getHomepageSectionRoute(values.section_key, "button_link"), secondary_button_link: getHomepageSectionRoute(values.section_key, "secondary_button_link") }; const result = id ? await supabase.from("homepage_sections").update(protectedValues).eq("id", id) : await supabase.from("homepage_sections").upsert(protectedValues, { onConflict: "section_key" }); if (result.error) throw new Error("تعذر حفظ قسم الصفحة الرئيسية"); revalidatePath("/"); return { ok: true }; }
export async function createGalleryItem(payload: { image_url: string; storage_path: string | null; caption_ar: string; sort_order: number; is_active: boolean }) { const supabase = await requireAdmin(); const { error } = await supabase.from("gallery_items").insert(payload); if (error) throw new Error("تعذر حفظ صورة المعرض"); revalidatePath("/"); return { ok: true }; }
export async function updateGalleryItem(id: string, payload: { caption_ar: string; sort_order: number; is_active: boolean }) { const supabase = await requireAdmin(); const { error } = await supabase.from("gallery_items").update(payload).eq("id", id); if (error) throw new Error("تعذر تحديث صورة المعرض"); revalidatePath("/"); return { ok: true }; }
export async function deleteGalleryItem(id: string, storagePath: string | null) { const supabase = await requireAdmin(); const { error } = await supabase.from("gallery_items").delete().eq("id", id); if (error) throw new Error("تعذر حذف صورة المعرض"); if (storagePath) await supabase.storage.from("product-images").remove([storagePath]); revalidatePath("/"); return { ok: true }; }
export async function savePromotion(payload: Omit<Promotion, "id"> & { id?: string }) { const supabase = await requireAdmin(); const { id, ...values } = payload; const link = values.button_link?.trim() || null; const trustedLink = isInternalApplicationRoute(link) ? getTrustedInternalRoute(link) : link; if (isInternalApplicationRoute(link) && !trustedLink) throw new Error("رابط الصفحة الداخلية غير معتمد."); const result = id ? await supabase.from("promotions").update({ ...values, button_link: trustedLink }).eq("id", id) : await supabase.from("promotions").insert({ ...values, button_link: trustedLink }); if (result.error) throw new Error("تعذر حفظ العرض"); revalidatePath("/"); revalidatePath("/shop"); return { ok: true }; }
export async function deletePromotion(id: string, storagePath: string | null) { const supabase = await requireAdmin(); const { error } = await supabase.from("promotions").delete().eq("id", id); if (error) throw new Error("تعذر حذف العرض"); if (storagePath) await supabase.storage.from("product-images").remove([storagePath]); revalidatePath("/"); revalidatePath("/shop"); return { ok: true }; }
