"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { LockKeyhole } from "lucide-react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { Button } from "@/components/ui/button";

export function AdminLogin({ setupRequired = false, storeName }: { setupRequired?: boolean; storeName: string }) { const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(""); const client = getSupabaseBrowserClient(); if (!client) { setError("أضيفي بيانات Supabase إلى ملف البيئة أولاً."); setLoading(false); return; } const result = await client.auth.signInWithPassword({ email, password }); if (result.error) setError("تعذر تسجيل الدخول. راجعي البريد وكلمة المرور."); else { router.push("/admin"); router.refresh(); } setLoading(false); } return <main className="flex min-h-screen items-center justify-center bg-[#eee7dc] px-5 py-24"><div className="w-full max-w-md rounded-[2rem] bg-cream p-7 soft-shadow sm:p-10"><div className="text-center"><span className="font-serif text-5xl tracking-[-.06em]">{storeName}</span><p className="eyebrow mt-4">لوحة إدارة المتجر</p></div>{setupRequired && <p className="mt-7 rounded-xl bg-gold/10 p-3 text-center text-xs leading-6 text-cocoa">أكملي إعداد Supabase وملف البيئة للوصول إلى لوحة الإدارة.</p>}<form onSubmit={submit} className="mt-8 space-y-5"><label className="block text-xs text-ink/55">البريد الإلكتروني<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="form-input" placeholder="admin@example.com" /></label><label className="block text-xs text-ink/55">كلمة المرور<input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="form-input" placeholder="••••••••" /></label>{error && <p className="rounded-xl bg-burgundy/10 p-3 text-xs text-burgundy">{error}</p>}<Button disabled={loading} className="w-full">{loading ? "جاري الدخول…" : <><LockKeyhole size={16} /> تسجيل الدخول</>}</Button></form></div></main>; }
